# This is a basic workflow to help you get started with Actions

name: gitflow3

on:
  workflow_dispatch:


jobs:
 
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "build"
        run: echo Hello, build!

  test:
    name: test
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "Hello, test!"

  ProdDeploy:
    name: ProdDeploy
    needs: test  
    runs-on: ubuntu-latest
    steps:
      - name: "ProdDeploy"
        run: echo "Hello, ProdDeploy!"


      - name: ServiceNow DevOps Get Update
        uses: ServiceNow/servicenow-devops-update-change@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          change-request-number: 'CHG123456'
          change-request-details: '{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}'

          
    
