# This is a basic workflow to help you get started with Actions

name: gitflow3

on:
  workflow_dispatch:


jobs:
 
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "build"
        run: echo Hello, build!

  test:
    name: test
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "Hello, test!"

  ProdDeploy:
    name: ProdDeploy
    needs: test  
    runs-on: ubuntu-latest
    steps:
      - name: "ProdDeploy"
        run: echo "Hello, ProdDeploy!"


      - name: ServiceNow DevOps Get Change
        uses: ServiceNow/servicenow-devops-get-change@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          change-details: ("attributes":{"number":"CHG0063235"}}
    
