# This is a basic workflow to help you get started with Actions

name: gitflow3

on:
  workflow_dispatch:

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: "build"
        run: echo Hello, build!

  test:
    name: test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "test"
        run: echo "Hello, test!"

  ProdDeploy:
    name: 'ProdDeploy'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          # ServiceNow Instance URL
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          # Orchestration Tool Id
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          # GitHub Context
          context-github: ${{ toJSON(github) }}
          # Display Name of the Job
          job-name: 'ProdDeploy'
          change-request: '{"attributes":{"requested_by":{"name": "Abel Tuter"},"assignment_group":{"name": "Change Management"},"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2023-09-07 11:59:59","end_date": "2023-09-09 11:59:59"}}'
          timeout: '3600'
          interval: '100'
          changeCreationTimeOut: '3600'
          abortOnChangeCreationFailure: true
          abortOnChangeStepTimeout: true
