# This is a basic workflow to help you get started with Actions

name: CI/CD Github Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: echo "Build"
  Test:

    runs-on: ubuntu-latest
    steps:
      - name: "Test Step of the workflow/pipeline"
        run: echo "Test Step"
  Deploy:
    runs-on: unbuntu-latest
    steps:
      - name: ServiceNow DevOps Change Automation
      # You may pin to the exact commit or the version.
      # uses: ServiceNow/servicenow-devops-change@373e092812580f05105089c20129e6efe347c8e5
      uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
          # ServiceNow Instance URL
          instance-url: 
          # Devops Integration User Name
          devops-integration-user-name: # optional
          # Devops Integration User Password
          devops-integration-user-password: # optional
          # Devops Integration Token
          devops-integration-token: # optional
          # Orchestration Tool Id
          tool-id: 
          # Display Name of the Job
          job-name: 'ProdDeploy'
          # Github Context
          context-github: 
          # The max. time in seconds to wait until the action should fail.
          timeout: # optional, default is 3600
          # The time in seconds to wait between trying the API.
          interval: # optional, default is 100
          # The customized inputs to create change with the requested details.
          change-request: 
          # The max. time in seconds to wait until change created.
          changeCreationTimeOut: # optional, default is 3600
          # This value will be used to resume or abort the pipeline if the change is not created within the mentioned time period in changeCreationTimeOut. 
          abortOnChangeCreationFailure: # optional, default is true
          # This value will be used to resume or abort the pipeline after a timeout has occurred in case a change step is still in a pending state.
          abortOnChangeStepTimeout: # optional, default is true
          # The customized inputs to process deployment gate job related change.
          deployment-gate: # optional
                
