# This is a basic workflow to help you get started with Actions

name: CI/CD Github Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: "Build"
        run: echo "Build"

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: "Test Step of the workflow/pipeline"
        run: echo "Test Step"

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets
        run: |
          if [ -z "$TEST_INSTANCE_URL" ]; then
            echo "SN_INSTANCE_URL is NOT set"
            exit 1
          else
            echo "SN_INSTANCE_URL is set"
          fi
        env:
          TEST_INSTANCE_URL: ${{ secrets.SN_INSTANCE_URL }}
